/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.cliente;

import proyectofinal.cliente.tcp.ClienteTCP;
import proyectofinal.cliente.udp.AudioClienteUDP;
import proyectofinal.cliente.udp.ClienteUDPMensaje;
import proyectofinal.cliente.udp.WebcamClientUDP;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Gerardo Jimenez Arguelles
 * @author José Jimenez Arguelles
 */
public class GUICliente extends javax.swing.JFrame {
    protected ClienteUDPMensaje clienteUDPMensajes; //Variable del socket del clienteUDP para mensajes.
    protected final String SERVER;;
    protected WebcamClientUDP webCam;
    protected AudioClienteUDP audio;
    ClienteTCP clienteTCP;

    /**
     * Creates new form Principal
     */
    public GUICliente(String ip) throws Exception{
        initComponents();
        SERVER = ip;
        clienteUDPMensajes = new ClienteUDPMensaje(SERVER,50000);;
        //Inicializamos el socket de mensajes
        clienteUDPMensajes.inicia(mensajesTextArea);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mensajesScrollP = new javax.swing.JScrollPane();
        mensajesTextArea = new javax.swing.JTextArea();
        mensajeTextField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();
        seleccionarArchivoButton = new javax.swing.JButton();
        rutaTextField = new javax.swing.JTextField();
        enviarArchivoButton = new javax.swing.JButton();
        videoLabel = new javax.swing.JLabel();
        iniciarButton = new javax.swing.JButton();
        detenerButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        restanteLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        transcurridoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tasaLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensajesTextArea.setEditable(false);
        mensajesTextArea.setColumns(20);
        mensajesTextArea.setRows(5);
        mensajesScrollP.setViewportView(mensajesTextArea);

        enviarButton.setText("Enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        seleccionarArchivoButton.setText("Seleccionar Archivo");
        seleccionarArchivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarArchivoButtonActionPerformed(evt);
            }
        });

        rutaTextField.setEnabled(false);

        enviarArchivoButton.setText("Enviar Archivo");
        enviarArchivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarArchivoButtonActionPerformed(evt);
            }
        });

        iniciarButton.setText("Iniciar");
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });

        detenerButton1.setText("Detener");
        detenerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Video llamada");

        jLabel3.setText("Tiempo Restante");

        restanteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restanteLabel.setText("-");

        jLabel4.setText("Tiempo Transcurrido");

        transcurridoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transcurridoLabel.setText("-");

        jLabel2.setText("Tiempo Total");

        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLabel.setText("-");

        jLabel6.setText("Tasa Transferencia");

        tasaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tasaLabel.setText("-");
        tasaLabel.setFocusable(false);

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tasaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(restanteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transcurridoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(292, 292, 292))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(seleccionarArchivoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rutaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enviarArchivoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iniciarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detenerButton1)
                        .addGap(256, 256, 256))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(mensajesScrollP, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(mensajeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviarButton)
                                .addGap(24, 24, 24)))
                        .addComponent(videoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(videoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(enviarButton)
                                .addComponent(mensajeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iniciarButton)
                            .addComponent(detenerButton1)
                            .addComponent(seleccionarArchivoButton)
                            .addComponent(rutaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enviarArchivoButton)
                            .addComponent(cancelButton)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(mensajesScrollP, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tasaLabel)
                            .addComponent(totalLabel)
                            .addComponent(restanteLabel)
                            .addComponent(transcurridoLabel))
                        .addGap(91, 91, 91))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarArchivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarArchivoButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File archivo = fileChooser.getSelectedFile();
        String nombreArchivo = archivo.getAbsolutePath();
        rutaTextField.setText(nombreArchivo);
    }//GEN-LAST:event_seleccionarArchivoButtonActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_enviarButtonActionPerformed
        // Codigo para recuperar el mensaje y enviarlo.
        String mensaje = mensajeTextField.getText();
        // Enviamos el texto del mensaje al socket.
        if(!mensaje.equals("")){
            clienteUDPMensajes.leerMensaje(mensaje);
            mensajesTextArea.append("Yo: " + mensaje + "\n");
            mensajeTextField.setText("");
        }
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void enviarArchivoButtonActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_enviarArchivoButtonActionPerformed
        if(!rutaTextField.getText().equals("")){
            File archivo = new File(rutaTextField.getText());
            try{
                clienteTCP = new ClienteTCP(SERVER,50001);
                clienteTCP.setLabels(tasaLabel,totalLabel,restanteLabel,transcurridoLabel);
                clienteTCP.leerArchivo(archivo);
                clienteTCP.inicia();
            }catch (Exception e) {
                System.err.println(e.getMessage());
                System.exit(1);
            }
        }
    }//GEN-LAST:event_enviarArchivoButtonActionPerformed

    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        try{
            webCam = new WebcamClientUDP(SERVER, 50003, videoLabel);
            webCam.inicia();
            audio = new AudioClienteUDP(SERVER);
            audio.iniciar();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_iniciarButtonActionPerformed

    private void detenerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerButton1ActionPerformed
        webCam.detener();
        audio.detener();
        clienteUDPMensajes.leerMensaje("Finaliza Transmision");

    }//GEN-LAST:event_detenerButton1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(clienteTCP != null){
            clienteTCP.cancelar();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton detenerButton1;
    private javax.swing.JButton enviarArchivoButton;
    private javax.swing.JButton enviarButton;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField mensajeTextField;
    private javax.swing.JScrollPane mensajesScrollP;
    private javax.swing.JTextArea mensajesTextArea;
    private javax.swing.JLabel restanteLabel;
    private javax.swing.JTextField rutaTextField;
    private javax.swing.JButton seleccionarArchivoButton;
    private javax.swing.JLabel tasaLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel transcurridoLabel;
    private javax.swing.JLabel videoLabel;
    // End of variables declaration//GEN-END:variables
}
